version: "3.5"
services:
  rchain-frontend:
    container_name: rchain-cloud-frontend
    image: rchaincommunity/rchaincloudfrontend
    networks:
    - rnode-net
  rchain-backend-standalone:
    container_name: rchain-cloud-backend-standalone
    image: rchaincommunity/rchaincloudbackend
    networks:
    - rnode-net

networks:
  rnode-net:
    name: rnode-net

volumes:
  rchain-cloud-data:
