version: "3.5"
services:
  rchain-frontend:
    container_name: rchain-cloud-frontend
    environment:
    - FRONTEND_PORT=${FRONTEND_PORT}
    - BACKEND_PORT=${BACKEND_PORT}
    - HTTPS=${HTTPS}
    - IP=${IP}
    build:
      context: frontend
      dockerfile: Dockerfile.rchaincloudfrontend
    ports:
    - 81:3000
    volumes:
    - ./frontend/:/home/node/app/
    - /etc/letsencrypt/live/rchain.cloud/fullchain.pem:/home/node/app/node_modules/webpack-dev-server/ssl
    depends_on:
    - rchain-backend-standalone
    networks:
    - rnode-net
  rchain-backend-standalone:
    container_name: rchain-cloud-backend-standalone
    environment:
    - FRONTEND_PORT=${FRONTEND_PORT}
    - BACKEND_PORT=10000
    - HTTPS=${HTTPS}
    - IP=${IP}
    build:
      context: backend
      dockerfile: Dockerfile.rchaincloudbackend
    volumes:
    - ./app:/root/app
    - ./app/node_modules:/root/app/node_modules:cached
    ports:
    - 10000:10000
    networks:
    - rnode-net

networks:
  rnode-net:
    name: rnode-net

volumes:
  rchain-cloud-data:
