version: "3.5"
services:
  rchain-frontend:
    container_name: rchain-cloud-frontend
    environment:
    - INTERNAL_FRONTEND_PORT=${INTERNAL_FRONTEND_PORT}
    - EXTERNAL_FRONTEND_PORT=${EXTERNAL_FRONTEND_PORT}
    - INTERNAL_BACKEND_PORT=${INTERNAL_BACKEND_PORT}
    - EXTERNAL_BACKEND_PORT=${EXTERNAL_BACKEND_PORT}
    - HTTPS=${HTTPS}
    - IP=${IP}
    image: rchaincommunity/rchaincloudfrontend
    ports:
    - ${EXTERNAL_FRONTEND_PORT}:${INTERNAL_FRONTEND_PORT}
  rchain-backend-standalone:
    container_name: rchain-cloud-backend-standalone
    environment:
    - INTERNAL_BACKEND_PORT=${INTERNAL_BACKEND_PORT}
    - EXTERNAL_BACKEND_PORT=${EXTERNAL_BACKEND_PORT}
    - HTTPS=${HTTPS}
    image: rchaincommunity/rchaincloudbackend
    ports:
    - ${EXTERNAL_BACKEND_PORT}:${INTERNAL_BACKEND_PORT}
networks:
  default:
    external:
      name: rnode-net